### ISSUE TITLE
web-client can start with `node app.js`

### ISSUE THREAD

**Issue by hygkui** [FrankHassanabad/Oauth2orizeRecipes#23]
```
 throw new TypeError('The super constructor to `inherits` must not ' +
          ^
TypeError: The super constructor to `inherits` must not be null or undefined.
    at Object.exports.inherits (util.js:728:11)
    at Object.<anonymous> (./node_modules/http-proxy/lib/http-proxy/index.js:111:17)
```

This problem was caused by the http-proxy, it need the version > 1.11.x
so change it to 1.13.2 will fix this.

**Comment by anhldbk** [comment]
@hygkui Thanks for the PR
